services:
  swh-deposit-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: swh-deposit
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-deposit:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    depends_on:
      - swh-deposit-db
      - swh-scheduler
      - prometheus-statsd-exporter
      - nginx
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-deposit
      VERBOSITY: 3
      DJANGO_SETTINGS_MODULE: swh.deposit.settings.production
      RPC_PORT: 5006
      SCRIPT_NAME: /deposit
    healthcheck:
      test: curl -f http://localhost:5006/deposit || exit 1
      retries: 6
    volumes:
      - "./conf/deposit.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-deposit/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-loader-deposit:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
      - ./env/workers.env
    user: swh
    environment:
      SWH_WORKER_INSTANCE: loader-deposit
      SWH_SCHEDULER_INSTANCE: http://nginx/rpc/scheduler/
    command: worker
    depends_on:
      - swh-storage
      - swh-scheduler
      - swh-deposit
      - amqp
      - prometheus-statsd-exporter
      - nginx
    volumes:
      - "./conf/loader-deposit.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-worker/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-indexer-journal-client-remd:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    user: swh
    env_file:
      - ./env/common_python.env
      - ./env/workers.env
    environment:
      SWH_WORKER_INSTANCE: indexer
      SWH_LOG_LEVELS: info
      POSTGRES_DB: swh-idx-storage
      SWH_SCHEDULER_INSTANCE: http://nginx/rpc/scheduler/
    command: journal-client extrinsic_metadata
    depends_on:
      - kafka
      - swh-storage
      - swh-idx-storage
      - swh-objstorage
      - nginx
    volumes:
      - "./conf/indexer.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-indexer/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
