services:
  # For Celery
  amqp:
    image: rabbitmq:3.13-management

  # Kafka related
  kafka:
    image: docker.io/confluentinc/confluent-local
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:9092
      KAFKA_NUM_PARTITIONS: 16
      KAFKA_LOG_CLEANUP_POLICY: compact
      KAFKA_LOG_DIRS: /var/lib/kafka/data/kraft-combined-logs

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui

  kafka-create-topics:
    # this is a short-lived service, it creates kafka topics and exits
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    depends_on:
      - kafka
    restart: on-failure
    entrypoint: []
    command: sh -c 'wait-for-it kafka:9092 -s --timeout=0 -- python /srv/softwareheritage/create_topics.py && echo OK && sleep 10m'
    volumes:
      - "./utils/create_topics.py:/srv/softwareheritage/create_topics.py:ro"

  # monitoring
  prometheus:
    image: prom/prometheus
    depends_on:
      - prometheus-statsd-exporter
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    restart: unless-stopped

  prometheus-statsd-exporter:
    image: prom/statsd-exporter
    command:
      - "--statsd.mapping-config=/etc/prometheus/statsd-mapping.yml"
    volumes:
      - "./conf/prometheus-statsd-mapping.yml:/etc/prometheus/statsd-mapping.yml:ro"
    restart: unless-stopped

  prometheus-rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    restart: unless-stopped
    environment:
      SKIP_QUEUES: "RPC_.*"
      MAX_QUEUES: 5000
      RABBIT_URL: http://amqp:15672
      LOG_LEVEL: warning

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      GF_SERVER_ROOT_URL: http://localhost/grafana
    volumes:
      - "./conf/grafana/provisioning:/etc/grafana/provisioning:ro"
      - "./conf/grafana/dashboards:/var/lib/grafana/dashboards"

  # cache
  memcache:
    image: memcached
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis-data:/data
    command:
      - "--save"
      - "60"
      - "1" # flush every minutes
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 1s
      timeout: 5s
      retries: 10

  # main web reverse proxy for many services
  nginx:
    image: nginx
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80"

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1

  docker-helper:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    command: rpc
    volumes:
      - "./services/docker-helper/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
      - "./services/docker-helper/app.py:/srv/softwareheritage/app.py:ro"
    depends_on:
      - docker-proxy
    healthcheck:
      test: curl -f http://localhost/public-port/ || exit 1
      retries: 6

  # SMTP service (used by keycloak and vault)
  smtp:
    image: axllent/mailpit
    # https://mailpit.axllent.org/docs/configuration/runtime-options/
    environment:
      MP_DATABASE: /srv/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_WEBROOT: mail
    ports:
      - "1025"
    volumes:
      - /srv

  # Scheduler
  swh-scheduler-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-scheduler
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-scheduler:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-scheduler
      SWH_SCHEDULER_CONFIG_FILE: /srv/softwareheritage/config.yml
      RPC_PORT: 5008
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5008 || exit 1
      retries: 6
    depends_on:
      - swh-scheduler-db
      - prometheus-statsd-exporter
    volumes:
      - "./conf/scheduler.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-scheduler-listener:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-scheduler
      SWH_LOG_LEVELS: info
      SWH_SCHEDULER_CONFIG_FILE: /srv/softwareheritage/config.yml
      BROKER_URL: amqp://amqp/
      WORKER_INSTANCES: listers, loader
      APP: swh.scheduler.celery_backend.config.app
    command: worker start-listener
    depends_on:
      - swh-scheduler
      - amqp
      - prometheus-statsd-exporter
    volumes:
      - "./conf/scheduler.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-scheduler-runner:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-scheduler
      SWH_LOG_LEVELS: info
      SWH_SCHEDULER_CONFIG_FILE: /srv/softwareheritage/config.yml
      BROKER_URL: amqp://amqp/
      WORKER_INSTANCES: listers, loader
      APP: swh.scheduler.celery_backend.config.app
    command: worker start-runner --period 10
    depends_on:
      - swh-scheduler
      - amqp
      - prometheus-statsd-exporter
    volumes:
      - "./conf/scheduler.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-scheduler-runner-priority:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-scheduler
      SWH_LOG_LEVELS: info
      SWH_SCHEDULER_CONFIG_FILE: /srv/softwareheritage/config.yml
      BROKER_URL: amqp://amqp/
      WORKER_INSTANCES: listers, loader
      APP: swh.scheduler.celery_backend.config.app
    command: worker start-runner --period 10 --with-priority
    depends_on:
      - swh-scheduler
      - amqp
      - prometheus-statsd-exporter
    volumes:
      - "./conf/scheduler.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-scheduler-runner-first-visits:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-scheduler
      SWH_LOG_LEVELS: info
      SWH_SCHEDULER_CONFIG_FILE: /srv/softwareheritage/config.yml
      BROKER_URL: amqp://amqp/
      WORKER_INSTANCES: listers, loader
      APP: swh.scheduler.celery_backend.config.app
    command: worker start-runner-first-visits --period 10
    depends_on:
      - swh-scheduler
      - amqp
      - prometheus-statsd-exporter
    volumes:
      - "./conf/scheduler.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-scheduler-schedule-recurrent:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-scheduler
      SWH_LOG_LEVELS: info
      SWH_SCHEDULER_CONFIG_FILE: /srv/softwareheritage/config.yml
      BROKER_URL: amqp://amqp/
      WORKER_INSTANCES: listers, loader
      APP: swh.scheduler.celery_backend.config.app
    command: worker schedule-recurrent
    depends_on:
      - swh-scheduler
      - swh-loader
      - amqp
      - prometheus-statsd-exporter
    volumes:
      - "./conf/scheduler.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-scheduler-update-metrics:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-scheduler
      SWH_SCHEDULER_CONFIG_FILE: /srv/softwareheritage/config.yml
    command: update-metrics
    depends_on:
      - swh-scheduler-db
    volumes:
      - "./conf/scheduler.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # Graph storage

  swh-storage-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-storage
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"
      - storage-data:/var/lib/postgresql

  swh-storage:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    depends_on:
      - swh-storage-db
      - swh-objstorage
      - kafka
      - kafka-create-topics
      - nginx
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-storage
      RPC_PORT: 5002
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5002 || exit 1
      retries: 6
    volumes:
      - "./conf/storage.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-storage/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # Storage for public access (masking applied)

  swh-masking-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-masking
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"
      - masking-data:/var/lib/postgresql

  swh-storage-public:
    image: swh/stack
    build: ./
    depends_on:
      - swh-storage
      - swh-masking-db
    command: rpc
    environment:
      POSTGRES_DB: swh-masking
      RPC_PORT: 5002
    healthcheck:
      test: curl -f http://localhost:5002 || exit 1
      retries: 6
    volumes:
      - "./conf/storage-public.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-storage-public/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
      - "./services/swh-storage-public/config-create-db.yml:/srv/softwareheritage/config-create-db.yml:ro"

  # Object storage

  swh-objstorage:
    build: ./
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    depends_on:
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    environment:
      RPC_PORT: 5003
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5003 || exit 1
      retries: 6
    volumes:
      - "./conf/objstorage.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-objstorage/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
      - objstorage-data:/srv/softwareheritage/objects

  # Indexer storage

  swh-idx-storage-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-idx-storage
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-idx-storage:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    depends_on:
      - swh-idx-storage-db
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-idx-storage
      RPC_PORT: 5007
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5007 || exit 1
      retries: 6
    volumes:
      - "./conf/indexer_storage.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-indexer/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # Web interface
  swh-web-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-web
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-web:
    build: ./
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    depends_on:
      - swh-idx-storage
      - swh-scheduler
      - swh-storage-public
      - swh-web-db
      - swh-search
      - memcache
      - prometheus-statsd-exporter
      - nginx
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-web
      VERBOSITY: 3
      DJANGO_SETTINGS_MODULE: swh.web.settings.production
    healthcheck:
      # use curl retry with exponential backoff in case service initialization takes too
      # much time (when static assets must be downloaded and compiled for instance)
      test: curl --retry 5 -f http://localhost:5004 || exit 1
      retries: 6
    volumes:
      - "./conf/web.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-web/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-web-cron:
    build: ./
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    depends_on:
      - swh-web
      - nginx
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-web
      VERBOSITY: 2
      DJANGO_SETTINGS_MODULE: swh.web.settings.production
    command: cron
    volumes:
      - "./conf/web.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-web/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # Lister Celery workers

  swh-lister:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
      - ./env/listers.env
      - ./env/workers.env
    user: swh
    environment:
      SWH_WORKER_INSTANCE: listers
      SWH_SCHEDULER_INSTANCE: http://nginx/rpc/scheduler/
    depends_on:
      - swh-scheduler
      - swh-scheduler-runner
      - amqp
      - swh-lister-maven-nginx
      - prometheus-statsd-exporter
      - nginx
    command: worker
    volumes:
      - "./conf/lister.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-worker/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-lister-maven-nginx:
    # Http server to host the maven extracted index for the maven lister
    image: nginx
    volumes:
      - "./conf/maven_index/:/usr/share/nginx/html:ro"

  # Loader + deposit checker Celery workers

  swh-loader:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
      - ./env/workers.env
    user: swh
    environment:
      SWH_WORKER_INSTANCE: loader
      SWH_SCHEDULER_INSTANCE: http://nginx/rpc/scheduler/
    command: worker
    depends_on:
      - swh-storage
      - swh-scheduler
      - amqp
      - nginx
      - prometheus-statsd-exporter
    volumes:
      - "./conf/loader.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-worker/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # Indexer workers

  swh-indexer-journal-client-oimd:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    user: swh
    env_file:
      - ./env/common_python.env
      - ./env/workers.env
    environment:
      SWH_WORKER_INSTANCE: indexer
      SWH_LOG_LEVELS: info
      POSTGRES_DB: swh-idx-storage
      SWH_SCHEDULER_INSTANCE: http://nginx/rpc/scheduler/
    command: journal-client origin_intrinsic_metadata
    depends_on:
      - kafka
      - swh-storage
      - swh-idx-storage
      - swh-objstorage
      - nginx
    volumes:
      - "./conf/indexer.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-indexer/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # Journal related

  swh-scheduler-journal-client:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    command: journal-client
    environment:
      SWH_LOG_LEVELS: info
    env_file:
      - ./env/common_python.env
    depends_on:
      - kafka
      - swh-scheduler
      - nginx
    volumes:
      - "./conf/scheduler_journal_client.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-counters:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    command: rpc
    environment:
      RPC_PORT: 5011
    env_file:
      - ./env/common_python.env
    depends_on:
      - redis
      - prometheus-statsd-exporter
    volumes:
      - "./conf/counters.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-counters/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
    healthcheck:
      test: curl -f http://localhost:5011 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  swh-counters-journal-client:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    command: journal-client
    env_file:
      - ./env/common_python.env
    depends_on:
      - kafka
      - redis
      - swh-counters
      - prometheus-statsd-exporter
      - nginx
    volumes:
      - "./conf/counters_journal_client.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-counters/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # Search related

  swh-search:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5010 || exit 1
      retries: 6
    environment:
      RPC_PORT: 5010
    env_file:
      - ./env/common_python.env
    depends_on:
      - prometheus-statsd-exporter
    volumes:
      - "./conf/search-memory.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-search/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-search-journal-client-objects:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    env_file:
      - ./env/common_python.env
    command: journal-client
    depends_on:
      - kafka
      - swh-search
      - nginx
    volumes:
      - "./conf/search_journal_client_objects.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-search/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-search-journal-client-indexed:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    command: journal-client
    env_file:
      - ./env/common_python.env
    depends_on:
      - kafka
      - swh-search
      - nginx
    volumes:
      - "./conf/search_journal_client_indexed.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-search/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  # GraphQL API

  swh-graphql:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    depends_on:
      - swh-storage
      - prometheus-statsd-exporter
      - nginx
    environment:
      RPC_PORT: 5013
    env_file:
      - ./env/common_python.env
    volumes:
      - "./conf/graphql.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-graphql/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5013 || exit 1
      retries: 6

volumes:
  redis-data:
  storage-data:
  masking-data:
  objstorage-data:
  kafka-data:
