version: "2.1"

services:
  swh-graph:
    image: swh/stack
    build: ./
    entrypoint: /entrypoint.sh
    environment:
      SWH_CONFIG_FILENAME: /graph.yml
    depends_on:
      - kafka
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    volumes:
      - "./conf/graph.yml:/graph.yml:ro"
      - "./services/swh-graph/entrypoint.sh:/entrypoint.sh:ro"
      - swh-graph-data:/srv/softwareheritage/graph


volumes:
  swh-graph-data:
