version: "2.1"

services:

  svix-db:
    image: postgres:16
    env_file:
      - ./env/svix-db.env
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  svix:
    image: svix/svix-server
    environment:
      WAIT_FOR: "true" # We want to wait for the default services
    env_file:
      - ./env/svix.env
    volumes:
      - "./conf/svix.toml:/config.toml:ro"
    depends_on:
      - redis
      - svix-db

  swh-webhooks-journal-client:
    image: swh/stack
    build: ./
    env_file:
      - ./env/common_python.env
    depends_on:
      - kafka
      - svix
      - nginx

    volumes:
      - "./conf/webhooks_journal_client.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-webhooks-journal-client/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-web:
    depends_on:
      - kafka
      - svix
      - nginx

  swh-web-cron:
    # we cannot really remove a service in an override compose file...
    command: noop
    deploy:
      replicas: 0
