services:
  swh-alter:
    image: swh/stack
    build: ./
    command: mock-graph
    volumes:
      - "./tests/alter_companion.py:/src/alter_companion.py:ro"
      - "./services/swh-alter/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
      - "./conf/alter.yml:/srv/softwareheritage/config.yml:ro"
      - "./conf/alter/age-identities.txt:/srv/softwareheritage/age-identities.txt:ro"

  cassandra-seed:
    # This container starts a Cassandra instance that must be used as the
    # contact-point for clients. This container will then make the client
    # discover other cassandra containers.
    # This container must not be scaled up; scale up th 'cassandra'
    # container instead.
    image: cassandra:4.1
    env_file:
      - ./env/cassandra.env
    entrypoint: /swh_entrypoint.sh
    volumes:
      - "./services/cassandra/swh_entrypoint.sh:/swh_entrypoint.sh:ro"
      - "./conf/cassandra-override.yaml:/cassandra-override.yaml:ro"

  cassandra:
    # Additional Cassandra instance(s), which may be scaled up, but not
    # down. They will automatically connect to 'cassandra-seed', and
    # 'cassandra-seed' will tell clients to connect to these 'cassandra'
    # containers to load-balance.
    image: cassandra:4.1
    entrypoint: /swh_entrypoint.sh
    volumes:
      - "./services/cassandra/swh_entrypoint.sh:/swh_entrypoint.sh:ro"
      - "./conf/cassandra-override.yaml:/cassandra-override.yaml:ro"
    env_file:
      - ./env/cassandra.env
    environment:
      CASSANDRA_SEEDS: cassandra-seed

  swh-cassandra-storage:
    image: swh/stack
    build: ./
    depends_on:
      - cassandra-seed
      - swh-objstorage
      - kafka
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    environment:
      CASSANDRA_SEEDS: cassandra-seed
      PYTHONUNBUFFERED: 1
      RPC_PORT: 5002
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5002 || exit 1
      retries: 6
    volumes:
      - "./conf/alter/storage_cassandra.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-storage/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-extra-objstorage:
    build: ./
    image: swh/stack
    depends_on:
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    environment:
      RPC_PORT: 5003
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5003 || exit 1
      retries: 6
    volumes:
      - "./conf/objstorage.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-objstorage/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-storage-replayer:
    image: swh/stack
    build: ./
    depends_on:
      - kafka
      - swh-storage-db
      - swh-cassandra-storage
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    command: replayer
    volumes:
      - "./conf/alter/replayer.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-storage/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-objstorage-replayer:
    image: swh/stack
    build: ./
    depends_on:
      - kafka
      - prometheus-statsd-exporter
      - swh-objstorage
      - swh-extra-objstorage
      - nginx
    env_file:
      - ./env/common_python.env
    command: replayer
    volumes:
      - "./conf/alter/content-replayer.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-objstorage/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
