services:
  keycloak-db:
    image: postgres:11
    env_file:
      - ./env/keycloak-db.env
    environment:
      # unset PGHOST as db service crashes otherwise
      PGHOST:

  keycloak:
    build: services/keycloak
    env_file:
      - ./env/keycloak.env
    entrypoint: /entrypoint.sh
    environment:
      JAVA_TOOL_OPTIONS: "-Dkeycloak.profile=preview
                          -Dkeycloak.profile.feature.token_exchange=enabled"
    volumes:
      - "./services/keycloak/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
      - "./services/keycloak/keycloak_swh_setup.py:/keycloak_swh_setup.py:ro"
    expose:
      - "8080"
    depends_on:
      - keycloak-db

  swh-web:
    depends_on:
      - keycloak
    volumes:
      - "./conf/web-keycloak.yml:/srv/softwareheritage/config.yml:ro"

  swh-deposit:
    depends_on:
      - keycloak
    environment:
      MEMCACHED: "yes"
    volumes:
      - "./conf/deposit-keycloak.yml:/srv/softwareheritage/config.yml:ro"

  swh-graphql:
    depends_on:
      - keycloak
    volumes:
      - "./conf/graphql-keycloak.yml:/srv/softwareheritage/config.yml:ro"
