services:
  swh-coarnotify-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: swh-coarnotify
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-coarnotify:
    image: swh/stack:${SWH_IMAGE_TAG:-latest}
    build: ./
    depends_on:
      - swh-coarnotify-db
      # - ldn-inbox
      - nginx
      - swh-storage
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-coarnotify
      VERBOSITY: 3
      DJANGO_SETTINGS_MODULE: swh.coarnotify.settings.production
      RPC_PORT: 5015
      SCRIPT_NAME: /coarnotify
    healthcheck:
      test: curl -f -I http://localhost:5009/coarnotify
      retries: 6
    volumes:
      - "./conf/coarnotify.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-coarnotify/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
  # ldn-inbox:
  #   image: antleaf/notify_ldn_inbox:1.2
  #   command: notify_ldn_inbox -host=http://localhost -port=8008 -debug=true
  #   ports:
  #     - "8008"

  # ldn-inbox-db:
  #   image: mongo:7.0.14
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password

  # ldn-inbox:
  #   build: https://github.com/seanwiseman/coar-notify-inbox.git
  #   environment:
  #     - MONGO_DB_URI=mongodb://root:password@ldn-inbox-db:27017
  #     - SCRIPT_NAME=/ldn-inbox
  #   depends_on:
  #     - ldn-inbox-db
