services:
  swh-graph:
    image: swh/stack
    build: ./
    depends_on:
      - kafka
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    volumes:
      - "./conf/graph.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-graph/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"
      - swh-graph-data:/srv/softwareheritage/graph

volumes:
  swh-graph-data:
