version: "2.1"

services:
  swh-vault-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: swh-vault
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-vault:
    image: swh/stack
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-vault
      RPC_PORT: 5005
    command: rpc
    healthcheck:
      test: curl -f http://localhost:5005 || exit 1
      retries: 6
    depends_on:
      - swh-vault-db
      - swh-objstorage
      - swh-storage
      - swh-scheduler
      - prometheus-statsd-exporter
      - nginx
    volumes:
      - "./conf/vault.yml:/srv/softwareheritage/config.yml.in:ro"
      - "./services/swh-vault/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-vault-worker:
    image: swh/stack
    build: ./
    command: worker
    env_file:
      - ./env/common_python.env
      - ./env/workers.env
    environment:
      SWH_SCHEDULER_HOST: swh-scheduler
      SWH_SCHEDULER_INSTANCE: http://nginx/rpc/scheduler/
    depends_on:
      - swh-vault
      - swh-storage
      - nginx
    volumes:
      - "./conf/vault-worker.yml:/srv/softwareheritage/config.yml:ro"
      - "./services/swh-vault/entrypoint.sh:/srv/softwareheritage/entrypoint.sh:ro"

  swh-scheduler-runner:
    environment:
      WORKER_INSTANCES: listers, loader, vault

  swh-scheduler-runner-priority:
    environment:
      WORKER_INSTANCES: listers, loader, vault
