services:
  elasticsearch:
    env_file:
      - ./env/elasticsearch.env
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    mem_limit: 1G

  swh-search:
    # overload main swh-search to use elasticsearch as backend
    depends_on:
      - elasticsearch
    volumes:
      - "./conf/search.yml:/srv/softwareheritage/config.yml:ro"

volumes:
  elasticsearch-data:
